// Practice/Node/react-task-tracker/src/components/Button.js
import PropTypes from 'prop-types'

const Button = ({color, text, onClick}) => {
  return <button onClick={onClick} className='btn' style={{backgroundColor: color}}>{text}</button>;

}

Button.defaultProps = {
    color: 'steelblue',
}

Button.propTypes = {
    text: PropTypes.string,
    color: PropTypes.string,
    onClick: PropTypes.func
}

export default Button

// Practice/Node/vue-task-tracker/src/components/Button.vue
<template>
    <button @click="onClick()" :style="{background: color}" class="btn" >{{text}}</button>
</template>

<script>
export default {
    name: 'Button',
    props: {
        text: String,
        color: String,
    },
    methods: {
        onClick() {
            this.$emit('btn-click')
        }
    }

}
</script>
